### ISSUE TITLE
Return separated output option 

### ISSUE THREAD

**Issue by huornlmj** [slimm609/checksec.sh#186]
It would be useful to have a return separated output / format option like so:

RELRO:	Partial RELRO
STACK CANARY: Canary found
NX:	NX enabled
PIE:	No PIE
RPATH:	No RPATH
RUNPATH:	No RUNPATH
FILE:	/bin/ls

One might want to simply share the output in a text field, email or IM but the default tab separated format clobbers coherency.  The only other options are token separated and difficult for non-tech people to understand quickly.

**Comment by Artoria2e5** [comment]
I mean, we could call `${CHK_FUNCTION} | ${FORMATTER}` at the end instead to do the `jq` job, but it feels a bit too contrieved...

**Comment by slimm609** [comment]
You need some type of structure to support more than 1 file, otherwise the separated output breaks down.  In the upcoming 3.0 release, it will switch to golang and include yaml output which will be the closest thing to what you are looking for.

```
- checks:
    canary: Canary Found
    fortified: "0"
    fortify_source: N/A
    fortifyable: "0"
    nx: NX enabled
    pie: PIE Enabled
    relro: Partial RELRO
    rpath: No RPATH
    runpath: No RUNPATH
    symbols: No Symbols
  name: tests/binaries/output/all
  ```
